# Generated by Django 4.2 on 2023-05-01 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок поста')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='news/images', verbose_name='Изображение поста')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Дата нашего поста')),
            ],
            options={
                'verbose_name': 'Новости',
            },
        ),
    ]
