# Generated by Django 4.1.6 on 2023-05-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Заголовок проекта')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Описание проекта')),
            ],
        ),
    ]
