# Generated by Django 4.1.6 on 2023-05-01 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('change_tasks', '0002_listproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250, verbose_name='заголовок задачи')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Описание задачи')),
                ('file', models.FileField(blank=True, upload_to='tasks/files', verbose_name='пдф документ')),
                ('Standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='change_tasks.listproject')),
                ('created_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
