# Generated by Django 4.1.6 on 2023-05-02 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('change_tasks', '0003_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listproject',
            options={'verbose_name': 'Список проектов', 'verbose_name_plural': 'Список проектов'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
