# Generated by Django 4.1.6 on 2023-05-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change_tasks', '0004_alter_listproject_options_tasks_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='assigned_to',
        ),
    ]
