# Generated by Django 4.1.6 on 2023-05-03 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('change_tasks', '0007_taskassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='change_tasks.listproject', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Задача создана пользователем'),
        ),
    ]
