# Generated by Django 4.1.6 on 2023-05-03 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('change_tasks', '0008_alter_tasks_standard_alter_tasks_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('email', models.EmailField(max_length=250, verbose_name='майл')),
                ('phone', models.CharField(max_length=100, verbose_name='телефон')),
                ('subject', models.CharField(max_length=100, verbose_name='сообщение')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата обращения')),
                ('answer_contact', models.CharField(default='', max_length=100, verbose_name='ответ администратора')),
                ('contact_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
