# Generated by Django 4.1.6 on 2023-05-04 14:16

import change_tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_tasks', '0009_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='file',
            field=models.FileField(blank=True, upload_to=change_tasks.models.save_lesson_files, verbose_name='пдф документ'),
        ),
    ]
