# Generated by Django 4.1.6 on 2023-05-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_tasks', '0010_alter_tasks_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='file',
            field=models.FileField(blank=True, upload_to='files', verbose_name='пдф документ'),
        ),
    ]
